### ISSUE TITLE
When I create a DefaultMeetingSession and call property audioVideo app freezes

### ISSUE THREAD

**Issue by OnLiveLTD** [aws/amazon-chime-sdk-ios#127]
I want to use aws-chime-sdk-ios in a nativescript project. When I create a DefaultMeetingSession and call property audioVideo app freezes. I suppose it is due to some classes were not properly exposed in ObjC

**Comment by OnLiveLTD** [comment]
It looks like the same code is executing in a loop, it looks a bit like audioVideo returns null and runtime is trying to parse it. The processor spins 100%. A few of our IOS developers have tried to debug it somehow, but we won't be able to do it without your help :(

**Comment by haifengx** [comment]
Hi, 

Have you followed the Objective-C demo app's [example](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoObjC/ViewControllerObjC.m#L93) to start audioVideo after creating the `DefaultMeetingSession` instance?

Can you provide more information such as console logs for us to better assist you? Thanks!

**Comment by twprzybysz** [comment]
Hello,
Yes, we follow the example. That's why after calling anything with audioVideo and start() caused freeze.

Following this issue https://github.com/NativeScript/ios-runtime/pull/1270 we discovered that the version of tns ios was 6.5.0 (the fix was in 6.5.1). Upgrade to newest version fixed freeze problem but not entirely:

```
CONSOLE LOG file:///app/0.js:139:24: TypeError: _this.meetingSession.audioVideo.start is not a function. (In '_this.meetingSession.audioVideo.start()', '_this.meetingSession.audioVideo.start' is undefined)
```
Same thing happens when we try to call startLocalVideo():

```
CONSOLE LOG file:///app/0.js:137:24: TypeError: _this.meetingSession.audioVideo.startLocalVideo is not a function. (In '_this.meetingSession.audioVideo.startLocalVideo()', '_this.meetingSession.audioVideo.startLocalVideo' is undefined)
```

Here's the snippet which we use to run the meeting:
```
public startMeeting({JoinInfo}: JoinMeetingResponse, meetingObservers?) {
    return this.requestPermissions().then(() => {
        this.isMuted = false;
        this.isVideoOn = true;
        const sessionConfiguration = this.createSessionConfiguration(JoinInfo);
        const meetingSession = DefaultMeetingSession.alloc().initWithConfigurationLogger(
            sessionConfiguration,
            this.logger,
        );
        this.meetingSession = meetingSession;
        this.meetingSession.audioVideo.startLocalVideo();
        return this.meetingSession;
    }).catch((e) => {
        console.log(e);
        console.log("Some error occurred");
    });
}
```
At first we where thinking that audioVideo is undefined so we tried 
```
console.log(this.meetingSession.audioVideo); 
```
and it returned:
```
CONSOLE LOG file:///app/0.js:137:24: AmazonChimeSDK.DefaultAudioVideoFacade
```
It looks like audioVideo is not the problem here.

Used Xcode version is 11.7.
tns -v 7.0.8

**Comment by grzywus** [comment]
When we debug nativescript app with chrome devtools we get this error:

`*** NSForwarding: warning: object 0x1028675b8 of class 'AmazonChimeSDK.DefaultAudioVideoFacade' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector +[AmazonChimeSDK.DefaultAudioVideoFacade resolveInstanceMethod:]
NativeScript caught signal 6.`

**Comment by OnLiveLTD** [comment]
@tianyux-amz it looks similar to this https://github.com/aws/amazon-chime-sdk-ios/issues/117 pls review it up.

**Comment by haifengx** [comment]
@twprzybysz @grzywus thanks for posting your code snippets.

I think the root cause of the issue is that the objc method signature generated from Swift has slight different name than its original. You probably want to call something like `self.meetingSession.audioVideo.startAndReturnError` and `self.meetingSession.audioVideo. startLocalVideoAndReturnError` depending on how NativeScript converts the JS method name to native.

Examples in our objc demo app
https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoObjC/ViewControllerObjC.m#L109
https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoObjC/ViewControllerObjC.m#L166

**Comment by haifengx** [comment]
BTW, we have a React Native demo app example showcasing how to use our native SDKs with cross-platform libraries: https://github.com/aws-samples/amazon-chime-react-native-demo, which might provide some level of guidance to your NativeScript project.
