### ISSUE TITLE
Xcode 11.4 Swift 4 integration has no Package.swift manifest

### ISSUE THREAD

**Issue by lingxiao** [aws/amazon-chime-sdk-ios#15]
**Describe the bug**
Trouble integrating SDK into project. Platform: Xcode 11.4 Swift 4, error: repo has no Package.swift manifest

**To Reproduce**
1. Start a new `Single View  App`, name it NewApp
2. Build  the app (CMD + B)
3. Go to File >> Swift Packages >> Add Package Dependency
4. When prompted, choose `NewApp`. Press next
5. When prompted to Choose Package Repository, past in: `https://github.com/aws/amazon-chime-sdk-ios/`
6. When prompted to Choose Package Options, choose the first option: `Up to next Major`
7. Press Next 

Alternatively, you can also follow the instructions here: https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app

**Expected behavior**
Should go to the next step in the flow.

**Logs**
Get error: `https://github.com/aws/amazon-chime-sdk-ios/ has no Package.swift manifest for version 0.5.0`

**Screenshots**
![Screen Shot 2020-04-21 at 4 41 03 PM](https://user-images.githubusercontent.com/1197405/79911850-128eeb00-83ef-11ea-8e34-e8307f0367e4.png)

**Test environment Info (please complete the following information):**
 - Device: iphone 11
 - OS: iOS 13.4.1
 - Version AmazonChimeSDK: [0.5.0]
 - Version AmazonChimeSDKMedia: [0.5.0]
* I am simply using the latest release on github. 

**Additional context**

**Comment by tianyux-amz** [comment]
Hi @lingxiao,

Thank you for your interest in AmazonChime mobile SDK! The mobile SDKs are not onboarded to package management systems yet (e.g. CocoaPods, Carthage, Swift Package Manager), so there is no `Package.swift` in our repo. We are working on onboarding them to these popular platforms for easier usage in the future.

To usage AmazonChime mobile SDK for now, please follow [the setup guide](https://github.com/aws/amazon-chime-sdk-ios#setup) and manually include the .framework files to your project.

Let me know if the manual integration works :)

Best,
Tianyu

**Comment by lingxiao** [comment]
what is the .frameworks file? I see an executable (.exec file), and a bunch of directories.

**Comment by lingxiao** [comment]
Hey @tianyux-amz  can I verify that my usage of Chime will be free until June 2020? Per documetation?

**Comment by tianyux-amz** [comment]
Hi @lingxiao, you need to deploy a serverless demo first. Detailed steps can be found in "Running the demo app" section in our [README](https://github.com/aws/amazon-chime-sdk-ios#3-deploy-serverless-demo). Note: deploying the serverless demo may incur extra charges in your AWS account.

The offer you mentioned is for Chime Apps (e.g. the Web, iOS and Android clients that you can use directly). Chime SDK is a different product and was not part of this offer. However, if you are eligible for COVID-19 related credits for AWS, then those can be applied for SDK usage. Please refer to [Chime Pricing](https://aws.amazon.com/chime/pricing/) page for more details on the offer and the SDK pricing model.

**Comment by lingxiao** [comment]
@tianyux-amz  the "step 3: Deploy the serverless demo from amazon-chime-sdk-js" link to the js page, and that is a demo as well, I think I am missing vital concepts here, and I have been digging into `AmazonChimeSDKDemo` and am confused by what it's doing:

1. The demo can only accept an invitation in `ViewController.swift` , followed by a controller for a specific session `MeetingViewController.swift`. How would you *create* a new meeting and invite people?  I see that on the Amazon-chime-skd-js page, there is this snippet:

```
const AWS = require('aws-sdk');
const { v4: uuid } = require('uuid');

// You must use "us-east-1" as the region for Chime API and set the endpoint.
const chime = new AWS.Chime({ region: 'us-east-1' });
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');

const meetingResponse = await chime.createMeeting({
  ClientRequestToken: uuid(),
  MediaRegion: 'us-west-2' // Specify the region in which to create the meeting.
}).promise();

const attendeeResponse = await chime.createAttendee({
  MeetingId: meetingResponse.Meeting.MeetingId,
  ExternalUserId: uuid() // Link the attendee to an identity managed by your application.
})
```
Which seem to allow me to create meetings, where is the doc for these API in swift?

2.  Going back to this, 
```
struct AppConfiguration {
    static let url = "YOUR_SERVER_URL"
    static let region = "YOUR_SERVER_REGION"
}
```
Conceptually, why is there a need for a server and region at all? What am I serving?

**Comment by hokyungh** [comment]
Hi @lingxiao . Let us know if  [Getting_Started](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/01_Getting_Started.md) helps.
1. So if you see [serverless handler join](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L130), 
```
  let meetingInfo = await getMeeting(title);
  if (!meetingInfo) {
    const request = {
      ClientRequestToken: uuid(),
      MediaRegion: region,
      NotificationsConfiguration: getNotificationsConfig(),
    };
    console.info('Creating new meeting: ' + JSON.stringify(request));
    meetingInfo = await chime.createMeeting(request).promise();
    await putMeeting(title, meetingInfo);
  }
```
it will create the meeting if it does not exist. Therefore, if `ViewController` makes request to the server, it will create new meeting if it does not exist, so technically, [Http Post](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/ViewController.swift#L74) will 
create meeting in the server, which will give necessary data to create [MeetingSession](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L47).
From this point, you can start the audio/video.

We do not provide API like invitation currently so that needs to be implemented by the builder.

For others to join the meeting, either from web or mobile demo app, they will need to supply same meeting ID.


2. This is the url where chime server will be running. If you run [serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless), you will obtain server url. You will specify region where to create the meeting so it is basically same as the `MediaRegion` you copied
```
const meetingResponse = await chime.createMeeting({
  ClientRequestToken: uuid(),
  MediaRegion: 'us-west-2' // Specify the region in which to create the meeting.
}).promise();
```
If you are unsure, you can just put us-east-1

Let us know if you have further question.

**Comment by mitankit** [comment]
@lingxiao Let us know if you have more questions around this ?

**Comment by mitankit** [comment]
Since there are no more questions from reporter, I am going to close the issue. Feel free to reopen or create a new one if you still have more issues.
