### ISSUE TITLE
Module Compilation Error - Swift

### ISSUE THREAD

**Issue by mohit67890** [aws/amazon-chime-sdk-ios#163]
**Describe the bug**
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.1 compiler.
I am integrating chime and using the latest xcode for iOS 14 support, however the framework is being compiled with previous versions for xcode.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/13609574/98552501-8a0d6480-22c4-11eb-9132-b3f541e42aef.png)

**Test environment Info (please complete the following information):**
 - Device: iPhone X
 - OS: 14.1
 - Version AmazonChimeSDK: 0.11.1
 - Version AmazonChimeSDKMedia: 0.7.1

**Comment by hokyungh** [comment]
Thank you for reporting. Could you check if workaround described [here]( https://github.com/Carthage/Carthage/issues/3019#issuecomment-711094475) works for you? So basically clear `VALID_ARCHS` and set `EXCLUDED_ARCHS`

**Comment by mohit67890** [comment]
Hi @hokyungh, the above method doesnt seem to work for me. I get the same module compilation error.

**Comment by hokyungh** [comment]
@mohit67890 Did you also try to clean build?

**Comment by mohit67890** [comment]
@hokyungh Yes, I did that. I still get the same error.

**Comment by hokyungh** [comment]
What Xcode version you are using?

**Comment by mohit67890** [comment]
@hokyungh, Its the recent one available on App store - Version 12.1

**Comment by hokyungh** [comment]
@mohit67890 do you mind sharing the repro steps like some settings you have currently?

I have created a new project in the Xcode 12.1 and import two frameworks, but I am not able to get build errors.

Xcode version: 12.1
Swift version: 5.3

Let me know if you can try creating fresh new project and importing two frameworks to see if you get any build errors.

**Comment by DeluxeAlonso** [comment]
I was facing the same error. I needed to install git-lfs:

`brew install git-lfs`

`git lfs install`

In my case, I was integrating the SDK through cocoapods and I also needed to clear the cache:

`rm -rf /Users/$USER/Library/Caches/CocoaPods`

Delete the Pods/ folder and then install the pods again with `pod install`.

All of these steps worked for me, I hope it also works for you @mohit67890.

**Comment by mohit67890** [comment]
Thank You @DeluxeAlonso & @hokyungh, However I'm still unable to get rid of this error. 
For reference, I'm using flutter as the development environment. 

I'm using this plugin https://github.com/eggnstone/eggnstone_amazon_chime, I would be great if you could take a look because I have tried everything possible.

**Comment by linsang21** [comment]
Hi @mohit67890,

Sorry for the delay. Were you be able to solve the problem?
It seems like the error is possible from the integration or setup you have with the 3rd party plugin. Since we couldn't repro under the same env by directly depending on the SDK (https://github.com/aws/amazon-chime-sdk-ios#setup).
We're looking forward to support Flutter in the future to be better address the concerns. At the same time, would you submit the issue to the regarding plugin?

**Comment by dylonChime** [comment]
I'll leave this open as a feature request to officially support the Flutter environment.

**Comment by linsang21** [comment]
Let's track Flutter support in the master issue: https://github.com/aws/amazon-chime-sdk-ios/issues/4

**Comment by dangerbacon** [comment]
For anyone troubleshooting the "error extracting version from module interface" in the future:  the issue for me was that the .swiftmodule files had CRLF line endings, and should have had LF endings, and XCode couldn't understand the file.  The root cause was that Git was configured to convert to Windows line endings, which I needed for other reasons.

Solution for me was to create a `.gitattributes` file to force this particular file type to LF endings:
`*.swiftinterface text eol=lf`

After removing and restoring all the .swiftinterface files, then cleaning and rebuilding, the problem disappeared.

I hope this helps someone!
