### ISSUE TITLE
Disconnecting from a meeting fails and leaves the meeting audio session active.

### ISSUE THREAD

**Issue by jpmunoz9** [aws/amazon-chime-sdk-ios#193]
Disconnecting from a meeting fails and leaves the meeting audio session active.

We started noticing it in:
Chime SDK: 0.12.1
Media SDK: 0.8.1

We also tried to reproduce this with following Android SDK but we never saw it happen:
Chime SDK: 0.8.1
Media SDK: 0.8.1

We reverted to the following builds as a workaround:
Chime SDK: 0.11.0
Media SDK: 0.7.0

Test Conditions:
- Chime SDK: 0.13.0
- Media SDK: 0.9.0
- Network Connection: Wifi - Excellent
- iOS: 14.3
- Device: iPhone X

Reproduction Rate: Roughly 1 in 20 attempts.

Steps to reproduce:
1. Join a meeting with audio and video that has at least 1 other participant.
2. Stay in the meeting for 3 seconds.
3. Leave the meeting.

Problem:
The audio session is still active and other participants can see you in the meeting.

Logs Captured:

When leaving the meeting succeeds:
2020-12-18 18:03:00.603478-0600 Meetings[4765:998236] [INFO] ViewController - API/DefaultAudioVideoFacade/stop
2020-12-18 18:03:00.603833-0600 Meetings[4765:998232] [INFO] ViewController - Stopping VideoClient
2020-12-18 18:03:00.734307-0600 Meetings[4765:997786] [INFO] ViewController - AudioClient State: finishDisconnecting Status: ok
2020-12-18 18:03:00.745344-0600 Meetings[4765:997786] [INFO] ViewController - videoClientDidStop
2020-12-18 18:03:00.745625-0600 Meetings[4765:998232] [INFO] ViewController - VideoClient is being destroyed

When leaving the meeting fails:
2020-12-18 18:37:44.437909-0600 Meetings[4825:1016844] [INFO] ViewController - API/DefaultAudioVideoFacade/stop
2020-12-18 18:37:44.438579-0600 Meetings[4825:1016844] [INFO] ViewController - Stopping VideoClient
2020-12-18 18:37:44.589417-0600 Meetings[4825:1015249] [INFO] ViewController - videoClientDidStop
2020-12-18 18:37:44.589730-0600 Meetings[4825:1016844] [INFO] ViewController - VideoClient is being destroyed

**Comment by hokyungh** [comment]
Thank you for reporting. Do you know if you can reproduce on iPhone X only or do you know if this is reproducible on any other phone? 

Could you also give us little more details on repro steps?
1. Can I test with web vs mobile? or does it usually happen with mobile vs mobile meeting?
2. Do you need to share your video or do we just wait for other displays to be shown?

**Comment by jpmunoz9** [comment]
Hi @hokyungh, we've also seen it happen on an iPhone 12. I don't think this is device specific.

1. Yes, you can test on web vs mobile. That's how I tested it.
2. Yes, both clients were sharing video and audio. I would just wait all video tiles to be shown and then leave the meeting.

**Comment by tianyux-amz** [comment]
Hi @jpmunoz9,

I tried to reproduce the issue in our demo app but failed. I did 50 attempts (since you mentioned the repro-rate is about 1/20) but I can always leave meeting properly and get `audioSessionDidStopWithStatus` callback as expected.

This is how I tried to reproduce the issue:

#### Environment
- Attendee1: Joined through web serverless demo (amazon-chime-sdk-js@2.2.1) on laptop.
- Attendee2: Joined through iOS demo app (with Chime SDK v0.12.1 and Media SDK v0.8.1) on iPhone 6s with iOS 12.2.

#### Test Steps
- Attendee1 joined meeting and enabled video.
- Attendee2 joined the same meeting and enabled video as well. Both attendees were able to see two videos and hear each other.
- Attendee2 left the meeting. Attendee1's roster was updated, and Attendee1 was not able to hear Attendee2 anymore.
- Repeat the above test 50 times with different variants, e.g. Attendee2 joined with CallKit, Attendee2 joined before Attendee1, Attendee2 left meeting muted, Attendee2 did not enable video, etc.

#### Two questions for you:
1. Were you testing your own application or the iOS demo app? If you were testing your own app, could you try to reproduce the issue with the iOS demo?
2. Were you able to reproduce the issue on other iOS versions? Based on your comment, the issue should be iOS version irrelevant (since you cannot reproduce the issue with SDK v0.11.0 on iOS 14.3), but just want to double check.

Best,
Tianyu

**Comment by NehaSalve1393** [comment]
I am also facing the same issue in my own app and I have also tested with demo app it is also having the same issue please replay ASAP

**Comment by tianyux-amz** [comment]
I tried to reproduce the issue with using iPhone 12 Pro with iOS 14.3 and iPhone 6s with iOS 14.3, but I still couldn't reproduce the issue.

@NehaSalve1393 did you reproduced the issue using the ReactNative demo app, or the iOS demo app?

**Comment by NehaSalve1393** [comment]
@tianyux-amz I tried with React native demo app

**Comment by tianyux-amz** [comment]
Got it, let me try to repro with that.

**Comment by tianyux-amz** [comment]
I was able to reproduce the issue in the latest ReactNative demo. This seems related to #200.

Env: iPhone 6s with iOS 14.3, running SDK v0.12.2 and Media v0.8.2.

Steps:
1. UserA joined meeting via web serverless demo.
2. UserB joined meeting via RN demo and enabled video. Noticed the gree light in the status bar.
3. UserB left meeting. Noticed the green light is still on. In the log I saw video client was stopped though:
```
RNDemo[4032:183886] [INFO] NativeMobileSDKBridge - API/DefaultAudioVideoFacade/stop
RNDemo[4032:183803] [INFO] NativeMobileSDKBridge - Stopping VideoClient
RNDemo[4032:183339] [INFO] NativeMobileSDKBridge - videoClientDidStop
```
4. AudioClient was not disconnected successfully. UserA can still hear voice from UserB.

**Comment by NehaSalve1393** [comment]
@tianyux-amz  is there any solution for this?

**Comment by tianyux-amz** [comment]
We are root-causing the issue and will let you know once we have more findings.

**Comment by tianyux-amz** [comment]
The issue was introduced in #151. Will talk to the PR author and come up with a proper fix.

**Comment by tianyux-amz** [comment]
PR for the fix is being reviewed.

**Comment by jpmunoz9** [comment]
Hi @tianyux-amz, for us it was also seen in our own React Native app. I'm glad you could reproduce this. Thank you.

**Comment by tianyux-amz** [comment]
We are preparing a hotfix release tonight. Will resolve the issue once the hotfix is out.

**Comment by tianyux-amz** [comment]
The fix was released. Please try out the latest SDK v0.13.1 and let us know if you run into any other issues. Thanks!

**Comment by NehaSalve1393** [comment]
@tianyux-amz now it's working fine.. Thank you so much for your quick help!
