### ISSUE TITLE
When does billing begin?

### ISSUE THREAD

**Issue by jonah-katz** [aws/amazon-chime-sdk-ios#263]
Which of these start billing?

- audioVideo.start()
- audioVideo.startLocalVideo()
- audioVideo.startRemoteVideo()
- audioVideo.addVideoTileObserver(observer)
- the creation of the meeting on the server side

Similarly, when does billing end?

**Comment by linsang21** [comment]
Hi @jonah-katz, I assume you're asking only client side billing, because running server might consumes AWS resources already if you follows our [sever demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless#serverless-demo).

You could refer to the pricing page for most detailed info: https://aws.amazon.com/chime/chime-sdk/pricing/

Till today -
*There is no direct charge to create a meeting session or attendee join tokens. You are charged $0.0017 for each minute that each attendee is joined to your meeting session from a client using Amazon Chime SDK, with audio, video, or content share.*

So `audioVideo.start()` should be the point when attendee join the meeting. Similarly, `audioVideo.stop()` should be when attendee actively leave the meeting, however the meeting could sometimes end for them because of errors, when no billing is charged.

**Comment by jonah-katz** [comment]
@linsang21 Got it! Thanks. And when does billing end? Do I need to do explicitly call .stop(), ie when app goes into background and/or terminated?

**Comment by jonah-katz** [comment]
context: was charged much more than I'd expect, so sounds like billing might be active even after app is terminated, unless you call .stop()

**Comment by linsang21** [comment]
Sorry to hear that. I'm not super familiar with the metering part but does the bill has the break down so that tells it's only from meetings, excluding other AWS services? And do you have any measuring on server side to tell if the total connection time is far off the one on bill? 

So the the charging is based on whether there's a meeting connection, it's highly depends on your app implementation. If you like to disconnect when goes to background, you should consider call .stop() at that time. Also make sure  to call .stop and clean up all the resources when app is about to terminated if possible. (You can take a look at our demo app for reference)

**Comment by jonah-katz** [comment]
Its not a huge bill since I just started developing, but its far more than I expected (I only tested for a couple minutes, but was charged almost a dollar). Its all chime.

Ok gotcha, will be more aggressive with th .stop()'s. Thanks
