### ISSUE TITLE
Live Broadcast Demo has stopped error

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#287]
![16191864298591 4 MBAC6DCE959087425FB4FFDABC1860B012](https://user-images.githubusercontent.com/57893099/115945670-9ffa9480-a4b4-11eb-87fb-58d0f92c25b9.png)

After successfully installing the demo App and I start Screen Share am getting this error

**Comment by ziyiz-amzn** [comment]
@adesun2k  Glad that you built and run the demo app. 

Could you please take a look at the screen share section of the README? https://github.com/aws/amazon-chime-sdk-ios#4-update-demo-app

Could you also kindly provide more context about your testing? 

    Device: [e.g. iPhone6]
    OS: [e.g. iOS8.1]
    Version AmazonChimeSDK: [e.g. 0.4.0]
    Version AmazonChimeSDKMedia: [e.g. 0.4.0]
    Can you reproduce this in the demo app? If you are reporting a crash:
    Are you using bitcode supported binaries?
    Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Comment by adesun2k** [comment]
AmazonChimeSDKDemo[2015:833845] PostLogger post request failed Error Domain= Code=403 "(null)"

**Comment by adesun2k** [comment]
let userDefaultsKeyMeetingId = "demoMeetingId"
    let userDefaultsKeyExternalMeetingId = "demoExternalMeetingId"
    let userDefaultsKeyCredentials = "demoMeetingCredentials"
    let userDefaultsKeyUrls = "demoMeetingUrls"

Please can where exactly will I get those especially "demoMeetingUrls" can you a sample data of what they look like precisely

**Comment by adesun2k** [comment]
Took me 3 days to figure this out and was almost giving on this. Thanks to Saviour JESUS.

in the demo app SampleHandler.swift 
`let appGroupId = "YOUR_APP_GROUP_ID"`
was supposed to be **_AppConfiguration.appGroupId_**

Please guys your demo app code is not consistent with your Documentation.

**Comment by zhinang-amazon** [comment]
Hi @adesun2k, sorry for the confusion. If you look at our [ReadMe](https://github.com/aws/amazon-chime-sdk-ios/#4-update-demo-app), it mentions that App Group ID in `SampleHandler.swift` needs to be replaced as well. The reason that it cannot be `AppConfiguration.appGroupId` is that these two files belong to two separate target `AmazonChimeSDKDemo` vs `AmazonChimeSDKDemoBroadcast`.

We will update our ReadMe to use CodeBlock MarkDown on `broadcastBundleId` and  `appGroupId` so that it's more visible.
