### ISSUE TITLE
Is there a way to play our own sound using chime sdk

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios#328]
Hi,

We need to play a sound when an attendee joins the meeting. When we try to play it using `AVAudioPlayer` without changing the category of `AVAudioSession`, the voice mixed up with the voices of attendees and we barely hear any sound. I just wanted to confirm that is there any class or method in your sdk which is responsible for playing sounds. If we change the category to `AVAudioSessionCategoryPlayback` with options `AVAudioSessionCategoryOptions.DuckOthers`, before playing the audio, does it cause any issues with audio stream from chime sdk during the meeting?

Thanks.

**Comment by linsang21** [comment]
Hi there, unfortunately the use case is not supported in our SDK yet. Because by default, the SDK collects audio from microphone and not take injected audio like we do for content share video. However, supporting audio source injection is on our roadmap, and should be covered by https://github.com/aws/amazon-chime-sdk-ios/issues/300. I'll close this issue as dedupe. Let us know if you have further questions.
