### ISSUE TITLE
Chime SDK with IVS

### ISSUE THREAD

**Issue by andresuhartanto** [aws/amazon-chime-sdk-ios#371]
Hi Guys,
so we are developing an app where a user can broadcast audio to others, in this case we are using IVS to broadcast the audio. The host have the option to accept a call and the caller will join the host and the voice will also broadcasted to other users. we managed use the IVS to do broadcasting, and the call also work with Chime however there's a small problem we are facing, other users cannot hear the caller's voice (not broadcasted) only the host can hear the caller's voice.
Anyone have any idea how can we solve this? 

Thank you ☺️

**Comment by achronop** [comment]
IVS captures the audio from host's michrophone. That's why you are able to hear it from the broadcast. In parallel chime captures the audio from the same michrophone and sends it to the caller. The voice from the caller is received from chime and "plays" in the speaker. So you need that audio, going to the speaker, to become also input of your IVR in parallel with host's michrophone. Not sure how to do that.
