### ISSUE TITLE
Transcripts isPartial Not Being Set to False 

### ISSUE THREAD

**Issue by namankedia27** [aws/amazon-chime-sdk-ios#442]
**Describe the bug**
I'm using live transcripts from the Chime API. We use the isPartial boolean to highlight the caption since it is active. Most times, once a new caption comes in, I get the transcriptEventDidReceive for the older caption that has isPartial = false. However, there are times isPartial remains true even for older captions. 

**Expected behavior**
isPartial shouldn't remain true for old captions. 

**Screenshots**

logs of instance of isPartial not getting set to false 
<img width="300" alt="Screen Shot 2022-04-04 at 3 44 33 PM" src="https://user-images.githubusercontent.com/89167740/163024422-b6d5b213-abe6-4f2a-bc0d-63e8f81d9c98.png">

<img width="300" alt="Screen Shot 2022-04-04 at 3 44 33 PM" src="https://user-images.githubusercontent.com/89167740/163024509-34781987-717e-44c5-adef-01df8aadff6c.PNG">

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]
 - Can you reproduce this in the demo app?
If you are reporting a crash:
 - Are you using bitcode supported binaries?
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Additional context**

**Comment by Chitz** [comment]
Thanks for reporting the issue.

Can you please share more details such as the rough timeline when the issue was observed, Chime Meeting ID and Region for the affected meeting where you could see `isPartial = true` issue for older transcripts? This will help us confirm if this is due to a known issue which we can prioritize, if needed.

In the meantime you can add similar logic as a temporary workaround to force finalize partial result for older transcripts, please refer JS SDK Demo App implementation for the workaround - 
https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L2175-L2183 

Also, if possible can you please provide test environment details as well.

**Comment by namankedia27** [comment]
Hey @Chitz ! I'm unable to provide an exact timeline of when this call occurred but I am able to reproduce the issue on my end pretty consistently on my end on both simulator and device. 

I've added a temporary workaround but would love if this could be fixed!

**Comment by Chitz** [comment]
Thanks @namankedia27 for the information. Will keep an eye on this issue and provide a fix for it, if needed.

Since you have a workaround in place, I'm resolving this ticket for now. Please feel free to reopen it if required.
