### ISSUE TITLE
How we can list audio output devices instead of input devices?

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-ios#465]
We are using listAudioDevices() function to get list of audio devices , and setAudioDevice() to select them , but we want to list output deives like there is a hook in React ( useSelectAudioOutputDevice() ) . Is there anything in native version we can use to list output devices ? 

this is what we are getting as of now,

`{
        description = "MicrophoneBuiltIn - audioHandset";
        label = MicrophoneBuiltIn;
    },
        {
        description = "Built-in Speaker - audioBuiltInSpeaker";
        label = "Built-in Speaker"; 
}`

**Comment by linsang21** [comment]
Hi @Saifak34, the SDK currently only support returning the input audio, [here](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/device/DefaultDeviceController.swift#L40). And the use case under consideration was the input and output is bundled, means you choose one input and the output is automated chosen for you. So in terms of selecting the audio device, input is sufficient.

Now there's no easy way to return output instead, except for a customized `DeviceContoller ` with your logic, maybe utilizing the system API for that.

**Comment by Saifak34** [comment]
Thank you for quick response,

**Comment by hvsw** [comment]
> Now there's no easy way to return output instead, except for a customized DeviceController with your logic, maybe utilizing the system API for that.

Reopening this one. Since [we still list ONLY INPUT devices](https://github.com/aws/amazon-chime-sdk-ios/blob/dc8e42cdd78021db1f0cef4be2fa713fc6cc5e01/AmazonChimeSDK/AmazonChimeSDK/device/DefaultDeviceController.swift#L40), how can I connect to an output-only device, like a Bluetooth speaker? Do I still need to build a custom `DeviceController` and wire it up?

**Comment by linsang21** [comment]
@hvsw I haven't test this case with our demo app, could you try if the SDK shows bluetooth speaker as available audio device? If not, I think it'd be cleaner for your case to directly use the [AVAudioSession](https://developer.apple.com/documentation/avfaudio/avaudiosession) to change the audio route.

**Comment by hvsw** [comment]
@linsang21 no, the SDK won't list output-only devices. This could be better documented somewhere.

# Context

## Use case
My specific use case supports attendees that are just **viewers**, so they connect to replicas and don't share audio or video. So the setup of an ouput-only device is to support this use case, and since the SDK only lists input devices I can't solve for this case through the SDK. 

I did some experimentation and am able to circumvent this, but since the audio resources are shared I want to minimize my interference to reduce bug surface area and let the SDK handle that(even if I need to configure something on the SDK, that's fine).

## Some investigation

Immediately after `audioSessionDidStartConnecting` I get a `AVAudioSession.routeChangeNotification` with reason `Category Changed` to now `playAndRecord`. I'm not doing this so I'm assuming the SDK (or its private parts) is, can you confirm? (FWIW I'm not using CallKit).

This category change to `playbackAndRecord`  when the audio session starts which makes iOS require/accept only routes with input ports. You can also see the same behavior on Apple's `Voice Memos` app for example by connecting to a Bluetooth speaker and tapping the record button and quickly pulling the control center to see the available ports in media center - you'll notice that immediately when you start/stop the recording, the LIST of available ports in the media center changes.

Here's a video showing the behavior with `Voice Memos`:

https://github.com/aws/amazon-chime-sdk-ios/assets/2053643/18154d6a-183a-4935-93f0-c568583b91aa

**Comment by hvsw** [comment]
For future reference, here's the reply I got from AWS support:

> Thank you for your patience throughout this case while we endeavour to look into the issue and reproduce the issue.
> 
> Great News! We have been able to successfully reproduce the issue and have identified a possible bug.
> 
> We will be rolling out the fix to ensure this is resolved for you. As soon as I have an ETA on deployment, I will reach back out.
> 
> I sincerely appreciate the patience once more throughout this case. All the very best my friend and speak to you as soon as I have an ETA available.
