### ISSUE TITLE
No such module 'AmazonChimeSDK'

### ISSUE THREAD

**Issue by yousefmoosavi** [aws/amazon-chime-sdk-ios#542]
CallKitManager.swift 

- in header error (when building project):

//
//  CallKitManager.swift
//  AmazonChimeSDKDemo
//
//  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//  SPDX-License-Identifier: Apache-2.0
//

import AmazonChimeSDK // No such module 'AmazonChimeSDK'
import AVFoundation
import CallKit
import UIKit

**Comment by linsang21** [comment]
Hi @yousefmoosavi, wondering did you follow the README step by step for integration? https://github.com/aws/amazon-chime-sdk-ios#include-amazon-chime-sdk-in-your-project
Also we might need more information to reproduce, can you fill in the questionnaire come with the template?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]
 - Can you reproduce this in the demo app?
If you are reporting a crash:
 - Are you using bitcode supported binaries?
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Additional context**
Add any other context about the problem here.
