### ISSUE TITLE
Roster list, Audio or Video of attendee is not coming once user share mobile screen with either  Skype or Teams

### ISSUE THREAD

**Issue by manindra86** [aws/amazon-chime-sdk-ios#55]
**Describe the bug**
Once the user does the screen sharing with Teams or Skype meeting then the Roster list, audio, and video of chime meeting is not showing.

**To Reproduce**
1. Start the meeting with Teams or skype 
2. Share the screen on teams or skype
3. Start the meeting and let attendees join the call and share the video
4. See the roster list or video both screens will blank.

**Expected behavior**
Roster list should be available and for Audio , video chime meeting should have the option to take  ownership of Audio, video devices

**Logs**
2020-06-09 23:42:54.141412+0530 MOBIINSPECT[317:15099] [ERROR] MeetingViewController - [004:307] [84871] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.

Test environment Info 
 - Device:  iPhone Xr
 - OS:  iOS 13.3
 - Version AmazonChimeSDK:  0.7.0
 - Version AmazonChimeSDKMedia: 0.5.0

**Comment by haifengx** [comment]
Thanks for reporting the issue! I'm able to reproduce it with a slightly simplified process (no need to share the screen):
1. Start a call in any other VoIP apps such as Chime, Skype, or just a normal phone call
2. In the app built with Chime SDK, start and join the meeting
3. Meeting roster list is blank

Builders have two options to address the issue:
1. Integrate with [CallKit](https://developer.apple.com/documentation/callkit) so that iOS manages the call switching experience. Examples include Chime and Skype
2. Check the status and show popup to notify user about the failure. Examples include Slack

For the 2nd option, there seems to be a bug in the SDK that `AudioVideoObserver::audioSessionDidStopWithStatus` is not triggered as expected. We will look into the issue and get back to you.

**Comment by sjmadsen** [comment]
I may be seeing this same problem with slightly different reproduction steps.

I have integrated my app with CallKit. When device A starts a meeting with device B, a VoIP notification is sent from the server to device B. iOS presents the incoming call UI so the user can answer the call and join the meeting.

The first time I do this in an app session, everything works fine. The second time, device B does not receive the `attendeesDidJoin` callback for _either_ the local or remote attendee. Device A only receives that callback for the local attendee, but not for device B's. Additionally, I get no audio on either device.

I'm using SDK 0.7.0 with the recent change for CallKit audio session handling. Device B passes `true` for `callKitEnabled:` while device A passes `false`.

**Comment by zhinang-amazon** [comment]
We are working on a fix to properly invoke `AudioVideoObserver::audioSessionDidStopWithStatus` in the scenario @manindra86 reported.

@sjmadsen Can you create a separate issue for your scenario? It's different from the original issue because the original issue is due to the fact that Chime SDK cannot take control of Audio and Video without CallKit integration. I suspect your issue is caused by not configuring `AVAudioSession` properly (setting `category` and `mode` more than once)

**Comment by zhinang-amazon** [comment]
@manindra86 The fix is out with SDK release v0.8.0 to throw `MediaError.audioFailedToStart` in this scenario.
Commit: https://github.com/aws/amazon-chime-sdk-ios/commit/aa20ec88b71f032ee42aafaab15a190d5b5d712d
