### ISSUE TITLE
AWSChimeSDKMessagingListChannelMembershipsForAppInstanceUserRequest not returning sorted channels based on last message timestamp

### ISSUE THREAD

**Issue by jwarmkessel** [aws/amazon-chime-sdk-ios#610]
**State your question**
I'm planning on implementing a polling mechanism to listen for updates to any of the channels. However, when I make this request the channels are unordered. Is there another request I should be using or some expected strategy I should be using to retrieve a list of channels with the most recent being channels with the most recent last message timestamp? 

**Which AWS Services are you utilizing?**
Chime

**Provide code snippets (if applicable)**
```
        guard let listChannelMembershipsRequest = AWSChimeSDKMessagingListChannelMembershipsForAppInstanceUserRequest()
        else {
            return
        }
        
        listChannelMembershipsRequest.appInstanceUserArn = appInstanceUserArn
        listChannelMembershipsRequest.chimeBearer = appInstanceUserArn
        listChannelMembershipsRequest.maxResults = 40
        listChannelMembershipsRequest.nextToken = nextToken

        awsChimeSDKMessagingClient?.listChannelMemberships(forAppInstanceUser: listChannelMembershipsRequest) { response, error in
            print(response)
            completion(response, error)
        }
```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 AWSChimeSDKMessaging (2.30.4)
 
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 Cocoapods
 - Swift Version : [e.g. 4.0]
 Swift 5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 Simulator 
 - iOS Version: [e.g. iOS 11.4]
 iOS 16
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by eliasdem** [comment]
ListChannelMembershipsForAppInstanceUser API doesn't support returning sorted channels based on last message timestamp, but it includes LastChannelMessage timestamp in the response for each channel, and you can sort the results on the client side. 

Instead of implementing your own polling mechanism, you probably want to use WebSockets instead where a connected user can get updates on messages, channel details, etc. More details: https://docs.aws.amazon.com/chime-sdk/latest/dg/websockets.html. Also consider using the prefetch feature, where you can get the top 50 channels that contain unread messages and the latest LastMessageTimestamp values https://docs.aws.amazon.com/chime-sdk/latest/dg/prefetch.html

Another alternative is to use the streaming capability to publish all channel events to a Kinesis Stream (https://docs.aws.amazon.com/chime-sdk/latest/dg/streaming-export.html) connected to OpenSearch or similar data store, and build your own APIs on top of that.
