### ISSUE TITLE
Get content size of the video

### ISSUE THREAD

**Issue by TomasPecuch** [aws/amazon-chime-sdk-ios#64]
Hello,

our app supports video calls in landscape mode only on iPads and in portrait mode only on iPhones. The issue we are facing is, that we have no way to detect whether the incoming video is in landscape or in portrait mode and when the device is rotated, the video will rotate as well even though the device rotation is disabled.

Is there any way to get the content size of the incoming video so we can adjust the layout?

**Comment by haifengx** [comment]
Hi,

Unfortunately for now the SDK is not exposing content size or aspect ratio of the video stream, but we did get the same feature request from other developers and I marked this as an "enhancement". Will provide future updates of this request here. Thanks!

**Comment by wanghaor-amzn** [comment]
Hi @TomasPecuch,

We start to work on this now. We plan to add a new API in VideoTileObserver that will inform you if the video stream content size is changed. Also, we will add height and width information in VideoTileState so that you can adjust the layout based on it.

We will let you know as soon as it is out. Thanks!

**Comment by antonrenzobenedict** [comment]
Hi @wanghaor-amzn, 

May we know when this enhancement will be released? 

Thanks!

**Comment by wanghaor-amzn** [comment]
Hi, @TomasPecuch @antonrenzobenedict 
We just released AmazonChimeSDK v0.8.0 and AmazonChimeSDKMedia v0.5.2. In this version, we added an API `videoTileSizeDidChange` in `VideoTileObserver`. Once you adopt this new API in you app, you will be notified whenever the size of video tile is changed. Also, we added `videoStreamContentWidth` and `videoStreamContentHeight` in `VideoTileState` so that you can access the size of the video stream from there.

Please let us know if you have any other questions. Thanks!

**Comment by SMzig** [comment]
Hello @antonrenzoreyes 

I'm facing the same issue did you find any solution for this?

**Comment by hokyungh** [comment]
@SMzig you can check for https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/VideoTileObserver.swift#L51 or https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/VideoTileState.swift#L20
