### ISSUE TITLE
Enqueued from com.apple.root.default-qos.overcommit

### ISSUE THREAD

**Issue by 76kennyboss** [aws/amazon-chime-sdk-ios#70]
Hello, 

Setup is as follows:
iOS Javascript initiating a meeting, and then subsequently iOS ObjC joins in.
I then switched cameras a couple of times on iOS Javascript.
This then causes iOS ObjC to crash with gibberish errors.
`Enqueued from com.apple.root.default-qos.overcommit `

![Screenshot 2020-07-15 at 8 03 01 PM](https://user-images.githubusercontent.com/65489759/87543060-9bf44780-c6d6-11ea-960c-6411710733da.png)

**Comment by linsang21** [comment]
Hi, thanks for contacting us. Before we looking into the issue, would you fill in the information with the following template?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Additional context**
Add any other context about the problem here.
