### ISSUE TITLE
RealtimeObserver delegate method for end meeting is not available

### ISSUE THREAD

**Issue by manindra86** [aws/amazon-chime-sdk-ios#82]
**Is your feature request related to a problem? Please describe.**
Start the meeting and let the attendee join in this meeting. Host attendee ends the meeting then in realtime observer there should be a delegate method that should get invoke after the meeting ended by host attendee. We have integrated the AmazonChime in our project and our requirement is Once Host attendee ends the meeting then all the attendee should get kick out from the current meeting using the event observer in ios SDK. 

**Describe the solution you'd like**
In AmazonChime web SDK there is  one callback method available i.e
audioVideoDidStop(sessionStatus: MeetingSessionStatus): void {}
same should be available in ios sdk.

**Describe alternatives you've considered**

**Additional context**

**Comment by updev0612** [comment]
right. I've implemented this manually with backend.

**Comment by prakash-partho** [comment]
Hi, I m also facing the same issue, Is there any update on this? I have this feature to be completed in my demo application, So please help me with it, it will be very helping, thanks in advance

**Comment by hokyungh** [comment]
Thank you we currently do not have this feature available like `end meeting for all.` I will add feature request and put it in our backlog as high priority. 

For workaround, you have data message feature currently available. [dataMessageDidReceived](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift#L621) and [sendDataMessage](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift#L174). You will need to add observer [addRealtimeDataMessageObserver](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift#L217). With this you can send and receive real time message. When meeting ends, you can send command to end meeting for each.

Let me know if you have further question.

**Comment by linsang21** [comment]
Hi @manindra86 If I understand the issue correctly, you were asking for the equivalent for JS callback `audioVideoDidStop(sessionStatus: MeetingSessionStatus)`. In fact, iOS does have the [audioSessionDidStopWithStatus(sessionStatus: MeetingSessionStatus)](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/AudioVideoObserver.swift#L41). It should be triggered when the meeting ended from server side. Let us know otherwise.

Also to clarify, `end meeting for all` is done at the [server side](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L96). Reference to [Web demo](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1467) for an example.
