### ISSUE TITLE
How many video participants can be shown at a time?

### ISSUE THREAD

**Issue by antonrenzobenedict** [aws/amazon-chime-sdk-ios#90]
Is it the same as the chime app (8 for mobile)  (16 for desktop)? from: https://aws.amazon.com/chime/faq/

**Comment by hokyungh** [comment]
That is correct. For mobile, the limit should be 8 currently.

We are currently discussing whether we can provide API for customer to increase the limit on mobile device.

**Comment by dchen-aws** [comment]
The builders can receive and render up to 8 (or the number of WebRTC supported hardware decoders on Android devices, whichever is lower) available videos based on chronological order using the mobile SDKs (note that this limit is only on receiving end, they can still send up to 16 videos today). You can listen to onVideoTileAdded or onVideoTileRemoved callback to bind or unbind the video tiles. Builders can additionally call pauseRemoteVideoTile to stop receiving video frames for certain video tile if not being displayed to save bandwidth and battery but it will not allow additional video tiles to be received. We don’t provide an API for builders to know the exact limit for Android (if different than 8), but it should be a rare case that a device is having fewer than 8 decoders (most devices today support 16). The team is looking into providing an API to return the limit so that it matches our logic in the SDK. We are also looking into the possibility of removing the hard limit of 8. We will keep everyone posted when these improvements will be be available. Hope this helps.

**Comment by antonrenzobenedict** [comment]
hi @dchen-aws, @hokyungh 

Thanks!
